name: 智能合约安全审计

on:
  # 每周一运行
  schedule:
    - cron: '0 1 * * 1'
  # 手动触发
  workflow_dispatch:
  # 添加推送触发
  push:
    branches: [ dev ]
    paths:
      - 'core_suite/tests/**.sol'
      - 'core_suite/contracts/**.sol'

jobs:
  audit:
    name: 运行智能合约审计
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: 安装Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: 安装审计工具
        run: |
          python -m pip install --upgrade pip
          pip install slither-analyzer mythril solc-select
          solc-select install 0.7.6
          solc-select use 0.7.6
      
      - name: 安装Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      
      - name: 安装依赖
        run: forge install
      
      - name: 运行Slither分析
        run: |
          cd core_suite
          mkdir -p reports/audit
          slither . --json reports/audit/slither.json
        continue-on-error: true
      
      - name: 运行Mythril分析
        run: |
          cd core_suite
          mkdir -p reports/audit
          myth analyze tests/*.sol --solc-json remappings.json --max-depth 10 --execution-timeout 300 --output json > reports/audit/mythril.json
        continue-on-error: true
      
      - name: 生成审计摘要报告
        run: |
          cd core_suite
          echo "# 智能合约安全审计报告" > reports/audit/summary.md
          echo "## 生成时间: $(date)" >> reports/audit/summary.md
          echo "## Slither 分析结果" >> reports/audit/summary.md
          echo "\`\`\`" >> reports/audit/summary.md
          cat reports/audit/slither.json | jq -r '.results.detectors[] | "- " + .impact + ": " + .description' 2>/dev/null || echo "Slither分析未生成有效结果" >> reports/audit/summary.md
          echo "\`\`\`" >> reports/audit/summary.md
          echo "## Mythril 分析结果" >> reports/audit/summary.md
          echo "\`\`\`" >> reports/audit/summary.md
          cat reports/audit/mythril.json | jq -r '.issues[] | "- " + .severity + ": " + .description' 2>/dev/null || echo "Mythril分析未生成有效结果" >> reports/audit/summary.md
          echo "\`\`\`" >> reports/audit/summary.md
        continue-on-error: true
      
      - name: 上传审计报告
        uses: actions/upload-artifact@v3
        with:
          name: audit-report
          path: core_suite/reports/audit
          if-no-files-found: warn
      
      - name: 创建Issue (发现高危漏洞时)
        if: always()
        run: |
          cd core_suite
          # 如果发现高危或关键漏洞，则创建issue
          HIGH_ISSUES=$(cat reports/audit/slither.json | jq -r '.results.detectors[] | select(.impact == "High" or .impact == "Critical")' 2>/dev/null | wc -l)
          if [ "$HIGH_ISSUES" -gt 0 ]; then
            gh issue create --title "安全审计发现高危漏洞" --body "自动安全审计发现 $HIGH_ISSUES 个高危或关键漏洞。请查看最新的审计报告详情。"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true 